#pragma once

// graphics:
// #define GAME_BOARD_PLAYER_X_OFFSET_RATIO (0.2)
#define GAME_BOARD_PLAYER_X_OFFSET_RATIO (0.1)
#define GAME_BOARD_RATIO (0.8)
// #define GAME_BOARD_WALL_WIDTH_RATIO (0.2) // Factor
#define GAME_BOARD_WALL_WIDTH_RATIO (0.2) // Factor

#define GAME_BOARD_PLAYER_SPEED_X_SCREENS_PER_SEC (0.1) // Factor
#define GAME_BOARD_PLAYER_SPEED_Y_SCREENS_PER_SEC (0.1) // Factor

// #define GAME_BOARD_WALL_COLORS (24, 84, 173)

#define NUMBER_HEIGHT_RATIO (3)

#define MANAGER_INITIAL_SCORE (0)
#define MANAGER_INITIAL_OBSTICLE_SPEED_PIX_PER_SEC (5)
// #define MANAGER_INITIAL_SHAPES_PER_SEC (9) NOT BAD
#define MANAGER_INITIAL_SHAPES_PER_SEC (1)
