#pragma once

// graphics:
#define GAME_BOARD_X_RATIO (80)
#define GAME_BOARD_Y_RATIO (80)
#define GAME_BOARD_WALL_WIDTH_RATIO (13) // Factor
#define GAME_BOARD_WALL_COLORS (24, 84, 173)

#define NUMBER_HEIGHT_RATIO (3)

#define MANAGER_INITIAL_SCORE (0)
#define MANAGER_INITIAL_OBSTICLE_SPEED_PIX_PER_SEC (200)
#define MANAGER_INITIAL_SHAPES_PER_SEC (9)
